name: Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: |
      !contains(github.event.head_commit.message, 'skip ci') &&
      !contains(github.event.head_commit.message, 'skip deploy')
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            /var/www/naotimes-webui/deploy.sh
